using iText.IO.Image;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using LearnAPI.Data;
using LearnAPI.Modal;
using LearnAPI.Models;
using Microsoft.AspNetCore.Mvc;
using OxyPlot;
using OxyPlot.Series;

namespace LearnAPI.Controllers
{
[ApiController]
[Route("api/[controller]")]
public class PdfController : Microsoft.AspNetCore.Mvc.ControllerBase
{
    private readonly LearnDataContext _dbContext;

    public PdfController(LearnDataContext dbContext)
    {
        _dbContext = dbContext;
    }

    [HttpGet("get/{id}")]
    public async Task<IActionResult> GetPdf(int id)
    {
        var pdfFile = await _dbContext.PdfFiles.FindAsync(id);

        if (pdfFile == null)
        {
            return NotFound("PDF not found.");
        }

        return File(pdfFile.Content, "application/pdf", pdfFile.FileName);
    }
    
    // [HttpPost("generate-and-save")]
    // public async Task<IActionResult> GenerateAndSavePdf([FromBody] PdfDataModel data)
    // {
    //     if (data == null || string.IsNullOrWhiteSpace(data.Content))
    //     {
    //         return BadRequest("Invalid data received.");
    //     }

    //     // Generate the PDF
    //     byte[] pdfBytes;
    //     using (var memoryStream = new MemoryStream())
    //     {
    //         var pdfWriter = new PdfWriter(memoryStream);
    //         var pdfDocument = new PdfDocument(pdfWriter);
    //         var document = new Document(pdfDocument);

    //         document.Add(new Paragraph("PDF Generated by iText7"));
    //         document.Add(new Paragraph($"Title: {data.Title}"));
    //         document.Add(new Paragraph($"Content: {data.Content}"));

    //         document.Close();
    //         pdfBytes = memoryStream.ToArray();
    //     }

    //     // Save PDF to the database
    //     var pdfFile = new PdfFile
    //     {
    //         FileName = $"{data.Title}.pdf",
    //         Content = pdfBytes,
    //         CreatedAt = DateTime.UtcNow
    //     };

    //     _dbContext.PdfFiles.Add(pdfFile);
    //     await _dbContext.SaveChangesAsync();

    //     return Ok(new { Message = "PDF generated and saved successfully", PdfId = pdfFile.Id });
    // }

    [HttpPost("generate-and-save")]
    public async Task<IActionResult> GenerateAndSavePdf([FromBody] PdfDataModel data)
    {
        if (data == null || string.IsNullOrWhiteSpace(data.Content))
        {
            return BadRequest("Invalid data received.");
        }

        // Generate the chart image
        byte[] chartImageBytes = GenerateChartImage(data.Title);

        // Generate the PDF
        byte[] pdfBytes;
        using (var memoryStream = new MemoryStream())
        {
            var pdfWriter = new PdfWriter(memoryStream);
            var pdfDocument = new PdfDocument(pdfWriter);
            var document = new Document(pdfDocument);

            // Add Title and Content
            document.Add(new Paragraph("PDF Generated by iText7"));
            document.Add(new Paragraph($"Title: {data.Title}"));
            document.Add(new Paragraph($"Content: {data.Content}"));

            // Add the chart to the PDF
            if (chartImageBytes != null)
            {
                var imageData = ImageDataFactory.Create(chartImageBytes);
                var image = new iText.Layout.Element.Image(imageData).SetAutoScale(true);
                document.Add(new Paragraph("Generated Chart:").SetFontSize(14));
                document.Add(image);
            }

            // Close the document
            document.Close();
            pdfBytes = memoryStream.ToArray();
        }

        // Save PDF to the database
        var pdfFile = new PdfFile
        {
            FileName = $"{data.Title}.pdf",
            Content = pdfBytes,
            CreatedAt = DateTime.UtcNow
        };

        _dbContext.PdfFiles.Add(pdfFile);
        await _dbContext.SaveChangesAsync();

        return Ok(new { Message = "PDF with chart generated and saved successfully", PdfId = pdfFile.Id });
    }

    // Method to generate chart using OxyPlot
    private byte[] GenerateChartImage(string title)
    {
        // Create a simple chart model
        var model = new PlotModel { Title = $"{title} - Sample Chart" };
        model.Series.Add(new LineSeries
        {
            Points = { new DataPoint(0, 0), new DataPoint(10, 20), new DataPoint(20, 10) },
            Color = OxyPlot.OxyColors.Blue
        });

        // Export the chart as a PNG image
        using (var stream = new MemoryStream())
        {
            var pngExporter = new OxyPlot.SkiaSharp.PngExporter { Width = 600, Height = 400 };
            pngExporter.Export(model, stream);
            return stream.ToArray();
        }
    }
}
}